image: maven:3-jdk-11

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B verify --file pom.xml

  branches:
    '{master,stage,release/*}':
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
      - step:
          name: Coverity Full Scan
          caches:
            - maven
          script:
            - export COV_STREAM=$BITBUCKET_REPO_SLUG-$BITBUCKET_BRANCH
            - export BUILD_URL=$BITBUCKET_GIT_HTTP_ORIGIN/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER
            - export CSA=cov-analysis-linux64-2020.12
            - curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/downloadFile.htm?fn=$CSA.tar.gz | tar -C /tmp -xzf -
            - curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE -o /tmp/$CSA/bin/license.dat $COV_URL/downloadFile.htm?fn=license.dat
            - export PATH=$PATH:/tmp/$CSA/bin
            - cov-configure --java
            - cov-build --dir idir --fs-capture-search $BITBUCKET_CLONE_DIR mvn -B package -DskipTests
            - cov-analyze --dir idir --ticker-mode none --strip-path $BITBUCKET_CLONE_DIR --webapp-security
            - cov-commit-defects --dir idir --ticker-mode none --url $COV_URL --stream $COV_STREAM --scm git --description $BUILD_URL --target Linux_x86_64 --version $BITBUCKET_COMMIT
      - step:
          name: Coverity Quality Gate
          script:
            - apt-get update && apt-get install -y jq
            - curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/OWASP%20Web%20Top%2010?projectId=$BITBUCKET_REPO_SLUG > results.json
            - if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi

  pull-requests:
    '**':
      - step:
          name: Coverity Incremental Scan
          caches:
            - maven
          script:
            - if [[ ! "${BITBUCKET_PR_DESTINATION_BRANCH}" =~ (master|stage|release/*) ]]; then exit; fi
            - export CHANGE_SET=$(git --no-pager diff origin/$BITBUCKET_PR_DESTINATION_BRANCH --name-only)
            - export COV_STREAM=$BITBUCKET_REPO_SLUG-$BITBUCKET_PR_DESTINATION_BRANCH
            - export CSA=cov-analysis-linux64-2020.12
            - curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/downloadFile.htm?fn=$CSA.tar.gz | tar -C /tmp -xzf -
            - curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE -o /tmp/$CSA/bin/license.dat $COV_URL/downloadFile.htm?fn=license.dat
            - export PATH=$PATH:/tmp/$CSA/bin
            - cov-configure --java
            - cov-run-desktop --dir idir --url $COV_URL --stream $COV_STREAM --build mvn -B package -DskipTests
            - cov-run-desktop --dir idir --url $COV_URL --stream $COV_STREAM --ignore-uncapturable-inputs true --present-in-reference false --exit1-if-defects true $CHANGE_SET
