image: maven:3-jdk-11

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B verify --file pom.xml

  branches:
    '{master,stage,release/*}':
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
      - step:
          name: Polaris Scan
          caches:
            - maven
          script:
            - curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
            - unzip -d /tmp -jo polaris_cli-linux64.zip
            - /tmp/polaris --co project.name=chuckaude-$BITBUCKET_REPO_SLUG analyze -w -- mvn -B package -DskipTests
