# example workflow for Coverity on Polaris in a docker container
name: cop-docker
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    container:
      image: maven:latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        POLARIS_PROJECT: ${{ github.event.repository.name }}
        POLARIS_ZIP: polaris_cli-linux64.zip
      run: |
        ls -ld $GITHUB_WORKSPACE
        git log -1 --format=%cd --date=iso-strict
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git log -1 --format=%cd --date=iso-strict
        apt update && apt install -y unzip
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/$POLARIS_ZIP
        unzip -d $RUNNER_TEMP -jo $POLARIS_ZIP && rm -f $POLARIS_ZIP
        $RUNNER_TEMP/polaris --co project.name=$POLARIS_PROJECT analyze -w
        #$RUNNER_TEMP/polaris --co project.name=$POLARIS_PROJECT --co project.branch=${{ github.ref_name }} \
        #  --co project.revision.name=${{ github.sha }} --co project.revision.date=$(git log -1 --format=%cd --date=iso-strict) analyze -w
