# example workflow for SRM scans using the Bridge CLI
name: srm-bridge-cli-win64
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  srm:
    runs-on: [self-hosted, windows]
    env:
      BRIDGE_SRM_URL: ${{ vars.SRM_URL }}
      BRIDGE_SRM_APIKEY: ${{ secrets.SRM_APIKEY }}
      BRIDGE_SRM_ASSESSMENT_TYPES: SAST,SCA
      BRIDGE_SRM_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_SRM_BRANCH_NAME: ${{ github.event.ref_name }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    - name: SRM Full Scan
      run: |
        Invoke-WebRequest -Uri ${{ vars.BRIDGECLI_WIN64 }} -OutFile bridge.zip
        Expand-Archive -Path bridge.zip -DestinationPath ${{ runner.temp }} -Force
        Remove-Item -Path bridge.zip -Force
        ${{ runner.temp }}/bridge-cli-bundle-win64/bridge-cli --stage srm
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true
