# example pipeline for Black Duck SCA scans using the Bridge CLI
trigger:
- main
- develop
pool:
  vmImage: windows-latest
variables:
  - group: sca316.poc.blackduck.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- powershell: |
    Invoke-WebRequest -Uri $env:BRIDGECLI_WIN64 -OutFile bridge.zip
    Expand-Archive -Path bridge.zip -DestinationPath $(Agent.TempDirectory) -Force
    Remove-Item -Path bridge.zip -Force
    $(Agent.TempDirectory)/bridge-cli-bundle-win64/bridge-cli --stage blackducksca
  env:
    BRIDGE_BLACKDUCKSCA_URL: $(BLACKDUCK_URL)
    BRIDGE_BLACKDUCKSCA_TOKEN: $(BLACKDUCK_API_TOKEN)
    # BRIDGE_DETECT_ARGS: --spring.config.location=""
  displayName: 'Black Duck SCA Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
