# example workflow for Black Duck scans using the Synopsys Detect extension
# https://marketplace.visualstudio.com/items?itemName=synopsys-detect.synopsys-detect
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DETECT_PROJECT_NAME: $(Build.Repository.Name)
  DETECT_PROJECT_VERSION_NAME: $(Build.SourceBranchName)
  DETECT_CODE_LOCATION_NAME: $(Build.Repository.Name)-$(Build.SourceBranchName)

steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'

- task: SynopsysDetectTask@8
  displayName: 'Black Duck Scan'
  inputs:
    BlackDuckService: poc329.blackduck.synopsys.com
    DetectArguments: '--detect.policy.check.fail.on.severities=BLOCKER'