# example pipeline for Black Duck SCA scans using the Black Duck Security Scan Extension for ADO
# https://marketplace.visualstudio.com/items?itemName=blackduck.blackduck-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: sca316.poc.blackduck.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'Black Duck Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
    DETECT_PROJECT_VERSION_NAME: $(Build.SourceBranchName)
    DETECT_CODE_LOCATION_NAME: $(Build.Repository.Name)-$(Build.SourceBranchName)
  inputs:
    blackducksca_url: $(BLACKDUCK_URL)
    blackducksca_token: $(BLACKDUCK_API_TOKEN)
    blackducksca_scan_full: true
    blackducksca_scan_failure_severities: 'BLOCKER'
    blackducksca_fixpr_enabled: true
    blackducksca_reports_sarif_create: true
    azure_token: $(System.AccessToken)
- task: BlackDuckSecurityScan@2
  displayName: 'Black Duck PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
    DETECT_PROJECT_VERSION_NAME: $(System.PullRequest.targetBranchName)
    DETECT_CODE_LOCATION_NAME: $(Build.Repository.Name)-$(System.PullRequest.targetBranchName)
  inputs:
    blackducksca_url: $(BLACKDUCK_URL)
    blackducksca_token: $(BLACKDUCK_API_TOKEN)
    blackducksca_scan_full: false
    blackducksca_prcomment_enabled: true
    azure_token: $(System.AccessToken)
