# example pipeline for Black Duck SCA scans using the Black Duck Security Scan Extension for ADO
# https://marketplace.visualstudio.com/items?itemName=blackduck.blackduck-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: poc222.blackduck.synopsys.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'Black Duck SCA Scan'
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
  inputs:
    blackducksca_url: $(BLACKDUCK_URL)
    blackducksca_token: $(BLACKDUCK_API_TOKEN)
    blackducksca_scan_failure_severities: 'BLOCKER'
    blackducksca_fixpr_enabled: true
    blackducksca_prcomment_enabled: true
    blackducksca_reports_sarif_create: true
    azure_token: $(System.AccessToken)
    mark_build_status: 'SucceededWithIssues'
    # include_diagnostics: true
- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
