# example pipeline for Coverity scans using the Black Duck Security Scan Extension for ADO
# https://marketplace.visualstudio.com/items?itemName=blackduck.blackduck-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: cnc.chuckaude.com
  - name: COVERITY_VIEW
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: ''
    ${{ else }}:
      value: 'Outstanding Issues'
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'Coverity Scan'
  inputs:
    coverity_url: $(COVERITY_URL)
    coverity_user: $(COV_USER)
    coverity_passphrase: $(COVERITY_PASSPHRASE)
    coverity_policy_view: $(COVERITY_VIEW)
    coverity_prcomment_enabled: true
    coverity_build_command: mvn -B -DskipTests package
    coverity_clean_command: mvn -B clean
    # coverity_local: true
    azure_token: $(System.AccessToken)
    include_diagnostics: false
    mark_build_status: 'SucceededWithIssues'
