# example pipeline for Polaris scans using the Synopsys Security Scan extension for ADO
# https://marketplace.visualstudio.com/items?itemName=synopsys-security-scan.synopsys-security-scan
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: poc.polaris.synopsys.com

steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'

- task: SynopsysSecurityScan@1
  displayName: 'Polaris Scan'
  inputs:
    scanType: polaris
    bridge_polaris_serverUrl: '$(BRIDGE_POLARIS_SERVERURL)'
    bridge_polaris_accessToken: '$(BRIDGE_POLARIS_ACCESSTOKEN)'
    bridge_polaris_assessment_types: 'SAST,SCA'
    bridge_polaris_application_name: 'chuckaude-$(Build.Repository.Name)'
    bridge_polaris_project_name: '$(Build.Repository.Name)'
    bridge_polaris_branch_name: '$(Build.SourceBranchName)'

- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
