# example pipeline for Polaris scans using the Black Duck Security Scan Extension for ADO
# https://marketplace.visualstudio.com/items?itemName=blackduck.blackduck-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: poc.polaris.blackduck.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'Polaris Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    polaris_server_url: $(POLARIS_SERVERURL)
    polaris_access_token: $(POLARIS_ACCESSTOKEN)
    polaris_assessment_types: 'SAST,SCA'
    polaris_application_name: chuckaude-$(Build.Repository.Name)
    polaris_project_name: $(Build.Repository.Name)
    polaris_branch_name: $(Build.SourceBranchName)
    polaris_reports_sarif_create: true
- task: BlackDuckSecurityScan@2
  displayName: 'Polaris PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    polaris_server_url: $(POLARIS_SERVERURL)
    polaris_access_token: $(POLARIS_ACCESSTOKEN)
    polaris_assessment_types: 'SAST,SCA'
    polaris_application_name: chuckaude-$(Build.Repository.Name)
    polaris_project_name: $(Build.Repository.Name)
    polaris_branch_name: $(Build.SourceBranchName)
    polaris_branch_parent_name: $(System.PullRequest.targetBranchName)
    polaris_prcomment_enabled: true
    azure_token: $(System.AccessToken)
