# example pipeline for SRM scans using the Black Duck Security Scan Extension for ADO
# https://marketplace.visualstudio.com/items?itemName=blackduck.blackduck-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: srm316.poc.blackduck.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'SRM Scan'
  inputs:
    srm_url: $(SRM_URL)
    srm_apikey: $(SRM_APIKEY)
    srm_assessment_types: 'SAST,SCA'
    coverity_build_command: mvn -B -DskipTests package
    coverity_clean_command: mvn -B clean
    include_diagnostics: false
    mark_build_status: 'SucceededWithIssues'
